# Generated by Django 3.0.6 on 2020-07-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "azure_object_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Last name"
                    ),
                ),
                ("azure_token_cache", models.TextField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
    ]
